name: grand
channels:
  - omnia
  - anaconda
  - conda-forge
dependencies:
  - python=3.6
  - openmm=7.3.1
  - mdtraj
  - parmed
  - openmmtools
  - pymbar
  - lxml
  - netcdf=1.4.2
  - libnetcdf=4.6.2
